# Generated by Django 4.2.13 on 2024-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
